[project]
name = "py-project-init"
version = "0.1.0"
description = "A python gui app to initialize new programming projects."
readme = "README.md"
authors = [
    { name = "Daniel Rösch", email = "droesch91@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
py-project-init = "py_project_init:main"
main = "py_project_init:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
